name: Deploy to Supabase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1.3.0
        with:
          version: 1.136.3
  
      - name: Check CLI version
        run: supabase --version
      - name: Ensure src/types directory exists
        run: mkdir -p src/types
      
      - name: Generate Supabase types
        run: |
          supabase gen types typescript --project-id $SUPABASE_PROJECT_REF --schema public > src/types/supabase.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: mbvzhvhsywcgmpsnrghn

   

    

 
