name: Deploy to Supabase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: bickoSiTiEff/setup-supabase-action@v1.1.0

      - name: Check CLI version
        run: supabase --version
      - name: Verify Supabase types are checked in
        run: |
          supabase gen types typescript --project-id $SUPABASE_PROJECT_REF --schema public > src/types/supabase.ts
      
          if [ -n "$(git status --porcelain src/types/supabase.ts)" ]; then
            echo "❌ Supabase types are out of sync. Please run the generator and commit the result."
            exit 1
          else
            echo "✅ Supabase types are up to date."
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: mbvzhvhsywcgmpsnrghn

    

 
