name: Deploy SQL to Supabase
on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run SQL files on Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.DATABASE_URL }}
        run: |
          for file in supabase/migrations/*.sql; do
            echo "Running $file..."
            psql "$DATABASE_URL" -f "$file"
          done
