name: Deploy SQL to Supabase
on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test TCP connection to Supabase
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          nc -4 -zv db.mbvzhvhsywcgmpsnrghn.supabase.co 5432

      - name: Run SQL migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          for file in supabase/migrations/*.sql; do
            echo "Running $file..."
            psql -4 "$DATABASE_URL" -f "$file"
          done




