name: Deploy SQL to Supabase
on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Check DATABASE_URL exists
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is EMPTY!"
            exit 1
          else
            echo "DATABASE_URL is set and ready to use."
          fi

      - name: Run SQL migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          for file in supabase/migrations/*.sql; do
            echo "Running $file..."
            psql "$DATABASE_URL" -f "$file"
          done

      - name: Test DB connection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql "$DATABASE_URL" -c '\dt'


