name: Run Supabase SQL Migrations
on:
  push:
    paths:
      - 'supabase/migrations/**.sql'
      - '.github/workflows/supabase-migrate.yml'
jobs:
  migrate:
    name: Supabase SQL Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Supabase CLI via Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install supabase/tap/supabase

      - name: Run Supabase migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.PROJECT_URL }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          supabase link --project-ref $SUPABASE_PROJECT_REF
          supabase db push
